hanghae-99-real-project/back-end

(0)routes/post.routes.js
(1)controllers/posts.controller.js
(2)services/posts.service.js
(3)repositories/posts.repository.js

가장 기본적인 post CRUL 작업본입니다,
수정해야 할 부분들은 있지만, 어느정도의 초안은 잡힌 상태입니다.

FEAT :  가장 기본적인 post CRUL 초안입니다

---

(0)routes/auth.routes.js
(1)controllers/auth.controller.js
(2)services/auth.service.js
(3)repositories/Users.repository.js
(3)repositories/auth.repository.js
(3)repositories/tokens.repository.js

redis를 이용해 토큰을 저장하는 부분은 마저 수정할 예정입니다.
당장은 미완성 코드입니다.

FEAT: 회원가입, 로그인 관련 기본적인 crud 기능 작성

---

middlewares/error-handler.js

Fix: (Brian)Error handling fixed

---

(0)routes/auth.routes.js
(0)routes/index.js
(0)routes/mypage.routes.js
(0)routes/poo.routes.js
(1)controllers/auth.controller.js
(1)controllers/mypage.controller.js
(1)controllers/poo.controller.js
(2)services/mypage.service.js
(2)services/poo.service.js
(3)repositories/mypage.repository.js
(3)repositories/poo.repository.js
app.js

add : (김용식) mypage, poo api 뼈대코드 작성

---

(0)routes/auth.routes.js
(0)routes/poo.routes.js
(2)services/auth.service.js
(2)services/childComment.service.js
(2)services/poo.service.js
middlewares/auth-middleware.js

FIX : (김용식) 서버실행가능

---

middlewares/auth-middleware.js

REFACTOR(조우상): 구조 재조정

---

(1)controllers/mypage.controller.js
(2)services/mypage.service.js
(3)repositories/mypage.repository.js
migrations/20230522082010-create-users.js
models/users.js

profile_url -> userPhoto 변경입니다.

EFAT :(김용식) 모델 수정

---

(0)routes/index.js
(0)routes/search.routes.js
(1)controllers/search.controller.js
(2)services/childComment.service.js
(2)services/comment.service.js
(2)services/search.service.js
(3)repositories/comment.repository.js
(3)repositories/search.repository.js
app.js
middlewares/error-handler.js

유저 검색, 게시글 검색, searchRouter 주석 변경, 터미널 색상 변경

Feat: 검색 기능

---

(0)routes/post.routes.js
modules/s3.js

S3 모듈 내부에서 사진을 여러개 요청하면 photoUrl에 계속 푸쉬해서 저장하도록 수정했습니다

FIx commit(조우상)  = {

---

(0)routes/post.routes.js
(1)controllers/users.controller.js
(2)services/users.service.js
(3)repositories/Users.repository.js
.github/workflows/cicd.yml
appspec.yml
models/users.js
scripts/deploy.sh

cicd 구현을 위한 쉘 스크립트 및 appspec.yml 작성
설정값 오류 수정
회원가입 수정. 모델 수정
설정되지 않은 값들에 대한 모델에 대한 널값의 허용.
userphoto를 photoUrl로 통일

fix(조우상): appspec.yml 작성, 설정값 오류 수정, photoUrl로 통일, 널값의 허용

---

(0)routes/index.js
(1)controllers/users.controller.js
models/posts.js

간단한 수정. photoUrl이 담기지 않던 버그 수정

fix(조우상): 간단한 수정. photoUrl이 담기지 않던 버그 수정

---

scripts/deploy.sh

기존에 실행하던거 죽이고, 새로운 파일로 실행하는 기능 추가

FIX(조우상) commit 

---

(0)routes/comment.routes.js
(0)routes/search.routes.js
(1)controllers/childComment.controller.js
(1)controllers/comment.controller.js
(1)controllers/search.controller.js
(2)services/childComment.service.js
(2)services/comment.service.js
(2)services/search.service.js
(3)repositories/comment.repository.js
(3)repositories/search.repository.js
migrations/20230522082010-create-users.js
migrations/20230522082036-create-poo.js
migrations/20230522082128-create-comments.js
models/Poos.js
models/comments.js
models/users.js

Fix: SQL, photoname, location search

---

(0)routes/auth.routes.js
(1)controllers/users.controller.js
(2)services/users.service.js
(3)repositories/Users.repository.js
modules/comment_s3.js
modules/poo_s3 .js
modules/user_s3.js

FIX commit(조우상) S3 모듈 수정.

---

(0)routes/childComment.routes.js
(0)routes/comment.routes.js
(1)controllers/childComment.controller.js
(1)controllers/comment.controller.js
(1)controllers/users.controller.js
(2)services/childComment.service.js
(2)services/comment.service.js
(2)services/posts.service.js
(2)services/users.service.js
(3)repositories/Users.repository.js
(3)repositories/childComment.repository.js
(3)repositories/comment.repository.js
migrations/20230522082128-create-comments.js
migrations/20230522082151-create-childcomments.js
models/childcomments.js
models/comments.js

Feat: 비밀 댓글 비밀 대댓글 경우의 수 다 따져서 구현 완료

---

(0)routes/auth.routes.js
(0)routes/index.js
(1)controllers/posts.controller.js
(1)controllers/users.controller.js
(2)services/posts.service.js
(2)services/users.service.js
(3)repositories/Users.repository.js
package-lock.json
package.json
passport/index.js

SA API명세서 양식에 맞게 코드 수정
소셜 로그인 구현 시도

FIX(조우상) commit

---

(0)routes/index.js
(0)routes/post.routes.js
(1)controllers/users.controller.js
(2)services/users.service.js

FIX(조우상) commit  = 병합오류로 인한 에러 해결

---

(2)services/users.service.js

FIX(조우상): 오타로 인한 오류 수정

---

scripts/deploy.sh

FEAT(조우상) commit

---

scripts/deploy.sh

진짜 진짜 찐 수정. 이젠 진짜 될거다. 한발자국 나갔다 cicd

FIX(조우상) 진짜 진짜 찐 수정. 이젠 진짜 될거다. 한발자국 나갔다 cicd

---

package.json
scripts/deploy.sh

FIX commi(조우상)

---

appspec.yml
scripts/deploy.sh
scripts/karyl2.sh

FIX commiwhdntkd조우상

---

scripts/deploy.sh
scripts/karyl.sh
scripts/karyl2.sh

아니 왜안되는데,, ㅠㅠㅠㅠㅠ
시행착오입니다.. 스크립트 파일 수정

FEAT(조우상) commit 

---

appspec.yml

FEAT조우상 commit 

---

appspec.yml
scripts/deploy.sh
scripts/karyl.sh
scripts/karyl2.sh

[FEAT(조우상) commit =](https://github.com/hanghae-99-real-project/back-end/commit/35e108930d6636787460b8ad093552cf31b27964)

FEAT(조우상) commit =

---

scripts/deploy.sh

fix(조우상): cicd 완성

---

(1)controllers/childComment.controller.js
(1)controllers/comment.controller.js
(2)services/childComment.service.js
(2)services/comment.service.js
middlewares/auth-middleware.js
middlewares/error-handler.js

로그인을 하지 않은 사용자도 조회를 할 수 있게 바꾸고, 비밀 댓글과 비밀 대댓글 로직 수정

Fix: Auth middleware, secret comment, secret childcomment

---

(1)controllers/childComment.controller.js
(2)services/childComment.service.js
(2)services/comment.service.js
(3)repositories/childComment.repository.js

비밀 댓글 & 비밀 대댓글 조회 부분 예외처리 & 빈값 배열로 내보내기

Fix: Secret comment & secret childcomment

---

.github/workflows/cicd.yml
scripts/deploy.sh
scripts/karyl.sh

[FIX(조우상): pm2 메니저 사용](https://github.com/hanghae-99-real-project/back-end/commit/7ed439d58eafbae71f7ed3a30fe417e623ff3f7e)

FIX(조우상): pm2 메니저 사용

---

scripts/deploy.sh

[FIX(조우상): pm2 메니저 명령어 변경](https://github.com/hanghae-99-real-project/back-end/commit/d1be268ab30d361875c492bd3fdc43cb65dc835f)

FIX(조우상): pm2 메니저 명령어 변경

---

(1)controllers/posts.controller.js
(2)services/posts.service.js
(3)repositories/posts.repository.js

FIX(조우상): CRUD 형식 수정

---

(1)controllers/users.controller.js
(2)services/users.service.js
(3)repositories/Users.repository.js
(3)repositories/posts.repository.js

[FIX(조우상) commit : CRUD 형식 수정]

FIX(조우상) commit : CRUD 형식 수정

---

(1)controllers/users.controller.js
(3)repositories/Users.repository.js

FIX(조우상) commit : 자기소개 주석 해제

---

(0)routes/search.routes.js
(1)controllers/search.controller.js
(2)services/search.service.js
(3)repositories/search.repository.js
migrations/20230522081907-create-posts.js
models/posts.js

Feat: Search poobox address

---

(1)controllers/posts.controller.js

쓸데없고 이상하고 알수없는 오류덩어리 스파게티 코드 삭제[

FIX(조우상) commit : 쓸데없고 이상하고 알수없는 오류덩어리 스파게티 코드 삭제[

---

(0)routes/poo.routes.js
(1)controllers/comment.controller.js
(1)controllers/poo.controller.js
(2)services/comment.service.js
(2)services/poo.service.js
(3)repositories/comment.repository.js
(3)repositories/poo.repository.js
migrations/20230522082128-create-comments.js
models/comments.js

Fix: Comment Latitude, Longitude, address

---

(1)controllers/posts.controller.js
(2)services/posts.service.js
(3)repositories/Users.repository.js
models/posts.js

FIX(조우상): post에 address 추가

---

(0)routes/poo.routes.js
(0)routes/users.routes.js
(1)controllers/users.controller.js
(2)services/poo.service.js
(2)services/users.service.js
(3)repositories/Users.repository.js
app.js
modules/cashemiddleware.js
modules/redisClient.js

add : (김용식) 푸박스 전체조회 캐싱 추가

---

(0)routes/users.routes.js

FIX(조우상): api 경로 수정

---

(1)controllers/users.controller.js

FIX(조우상): 패스워드 인증 삭제

---

(3)repositories/Users.repository.js
scripts/deploy.sh

FIX(조우상): 로그인에 폰넘버 받기로 수정

---

(1)controllers/users.controller.js
(2)services/users.service.js
(3)repositories/Users.repository.js
migrations/20230522082010-create-users.js
models/users.js

[Fix(조우상): 로그인 회원가입 기능 수정. 형민님과 맞춘대로]

Fix(조우상): 로그인 회원가입 기능 수정. 형민님과 맞춘대로

---

(1)controllers/posts.controller.js
(1)controllers/users.controller.js
(2)services/users.service.js
models/userDao.js

FEAT(조우상): 소셜로그인 기본 구현

---

(0)routes/reportPoo.routes.js
(1)controllers/reportPoo.controller.js
(2)services/reportPoo.service.js
(3)repositories/reportPoo.repository.js
migrations/20230530122338-create-reportpoos.js
models/reportpoos.js

Feat: 실종 신고 등록 기능 구현 완료

---

migrations/20230522081907-create-posts.js
models/posts.js
scripts/deploy.sh

fix(조우상): 스크립트 수정

---

(2)services/users.service.js
(3)repositories/Users.repository.js
middlewares/auth-middleware.js
scripts/karyl.sh

Fix(조우상): 미들웨어 검증부분 수정

---

middlewares/auth-middleware.js
scripts/deploy.sh

fix(조우상): 몰라

---

scripts/deploy.sh

FIX(조우상): 쉘스크립트 수정

---

(1)controllers/users.controller.js
(2)services/users.service.js

FIX(조우상): 소셜로그인 디버깅

---

(2)services/users.service.js

[FIX(조우상): 라이브러리 추가](https://github.com/hanghae-99-real-project/back-end/commit/548bf501faf951015edadd2b9b09463f1206d79b)

FIX(조우상): 라이브러리 추가

---

appspec.yml

[fix (조우상): 야메파일 수정](https://github.com/hanghae-99-real-project/back-end/commit/042fbfcc6ecff52c7a3c7ba447824b1a68c18f7e)

fix (조우상): 야메파일 수정

---

(0)routes/users.routes.js
(1)controllers/users.controller.js
(2)services/search.service.js
(2)services/users.service.js
migrations/20230522081907-create-posts.js

뭐시 중한데 서버야 정신좀 차려라

---

(2)services/users.service.js

[fix(조우상): 파일 경로를 조금 더 섬세하게 수정](https://github.com/hanghae-99-real-project/back-end/commit/abdc70298df37dc11879059a57d3854cef5783fa)

fix(조우상): 파일 경로를 조금 더 섬세하게 수정

---

(2)services/users.service.js

fix(조우상)소셜미디어 디버깅 아니 왜안되는데 되게해줘요 

---

(2)services/users.service.js

[FIX(조우상):왜안돼? 디버깅 뭐야 이건 뭔데 왜 안돼? 아직 1단계인데 이건 왜안돼??](https://github.com/hanghae-99-real-project/back-end/commit/df16fa31a8f6addf6353ac2e5b4cb0455968d728)

FIX(조우상):왜안돼? 디버깅 뭐야 이건 뭔데 왜 안돼? 아직 1단계인데 이건 왜안돼??

---

(1)controllers/users.controller.js

FIX(조우상): 히히 디버깅

---

(1)controllers/users.controller.js
(2)services/users.service.js

fix(조우상): 화가 난ㄴ다화가나

---

(0)routes/notification.routes.js
(1)controllers/notification.controller.js
(2)services/childComment.service.js
(2)services/comment.service.js
(2)services/notification.service.js
(3)repositories/notification.repository.js
migrations/20230522081907-create-posts.js

Feat: Post & Get notifications

---

(2)services/users.service.js

[FIX(조우상):ㅁㄴㅁ나오리ㅏㅁ농ㄹ으아앙아아앙ㄱㅇ강가각ㄱㄱㄱ!!!! 되라고 좀 하](https://github.com/hanghae-99-real-project/back-end/commit/44f622eb298dcb035199056a120eb211803a4083)

FIX(조우상):ㅁㄴㅁ나오리ㅏㅁ농ㄹ으아앙아아앙ㄱㅇ강가각ㄱㄱㄱ!!!! 되라고 좀 하

---

(2)services/users.service.js

[fix(조우상): 소셜로그인 기능 콘솔 로그 추가](https://github.com/hanghae-99-real-project/back-end/commit/3793938e2d87a49ecd981cad8d5c40a9eb21cc2c)

fix(조우상): 소셜로그인 기능 콘솔 로그 추가

---

app.js

fix : (김용식) cors 옵션 수정

---

(1)controllers/posts.controller.js
migrations/20230522081907-create-posts.js
models/posts.js

FIX(조우상): post CRUD 변경.

---

(2)services/users.service.js

[try(조우상): 이상한 오류에 대한 트라이 트라이](https://github.com/hanghae-99-real-project/back-end/commit/d00ec176ec7d39556d5b1d0c74e2190dd6329a66)

try(조우상): 이상한 오류에 대한 트라이 트라이

---

(2)services/users.service.js

[fix(조우상): 액시오스 카카오 요청 형식 수정](https://github.com/hanghae-99-real-project/back-end/commit/6240a714493f84a4633a512b8626fbc1e8af5e2c)

fix(조우상): 액시오스 카카오 요청 형식 수정

---

(1)controllers/posts.controller.js
(3)repositories/posts.repository.js

[fix(조우상): 테스트를 위한 views와 status 주석처리](https://github.com/hanghae-99-real-project/back-end/commit/870dd2d1a2392529c8eed6f947504965063902f6)

fix(조우상): 테스트를 위한 views와 status 주석처리

---

migrations/20230522081907-create-posts.js
models/posts.js

[fix(조우상): 테스트를 위한 views 주석처리](https://github.com/hanghae-99-real-project/back-end/commit/92fe19194326f9ef5966a538fff22b1995985abd)

fix(조우상): 테스트를 위한 views 주석처리

---

models/posts.js

테스트를 위한 주석처리

---

(1)controllers/posts.controller.js
(3)repositories/posts.repository.js
migrations/20230522081907-create-posts.js
models/posts.js

[fix(조우상): 테스트를 위해 해뒀던 주석 해제](https://github.com/hanghae-99-real-project/back-end/commit/8119b539a34ba20630a1408844cb4c595035ee64)

fix(조우상): 테스트를 위해 해뒀던 주석 해제

---

(1)controllers/users.controller.js
(2)services/users.service.js
(3)repositories/Users.repository.js
package-lock.json
package.json

이제 데이터 베이스 속 데이터가 전부 털려도 사용자가 사용하는 비밀번호를 알 수 없습니다!
대신, 로그인 할 수 없습니다!

FEAT(조우상): bcrypt를 이용한 비밀번호 암호화 복호화

---

(0)routes/users.routes.js
(1)controllers/users.controller.js

[Fix(조우상): 암호화와 복호화를 통해 비밀번호를 관리합니다. 이제 데이터베이스가 털려도 사용자의 비밀번호를 알아내는 것은…](https://github.com/hanghae-99-real-project/back-end/commit/d662efc38c5c94ba70ab4fa71c88e6924d1770d1) 
… 조금 더 어려워졌습니다!
안심하세요!

Fix(조우상): 암호화와 복호화를 통해 비밀번호를 관리합니다. 이제 데이터베이스가 털려도 사용자의 비밀번호를 알아내는 것은…   … 조금 더 어려워졌습니다!  안심하세요!

---

(0)routes/users.routes.js
models/posts.js

FIX(조우상): 오타 수정

---

(0)routes/users.routes.js

Commits on Jun 6, 2023
[fix(조우상): 테스트로 인한 주석처리](https://github.com/hanghae-99-real-project/back-end/commit/c9e994140611cd4ffa8f16e2d02c51abca386254)

Commits on Jun 6, 2023 fix(조우상): 테스트로 인한 주석처리

---

(2)services/posts.service.js
(2)services/users.service.js

[fix(조우상): 쿼리스트링으로 변환](https://github.com/hanghae-99-real-project/back-end/commit/16ace36f502e116573145c044aa4f44af70f3831)

fix(조우상): 쿼리스트링으로 변환

---

modules/s3.js

[fix (조우상): 확장자 제한 해제](https://github.com/hanghae-99-real-project/back-end/commit/1d8246882d431ae04bdacab9af371d6b1e14de87)

fix (조우상): 확장자 제한 해제

---

(2)services/posts.service.js

[fix(조우상): getpost에 lostphotourl 추가](https://github.com/hanghae-99-real-project/back-end/commit/7199a4fb168e80b12d692c77aa5a228255cf4290)

fix(조우상): getpost에 lostphotourl 추가

---

(0)routes/users.routes.js
(1)controllers/users.controller.js
(2)services/users.service.js
(3)repositories/Users.repository.js

[FEAT (조우상) : 마이페이지 수정 기능 추가](https://github.com/hanghae-99-real-project/back-end/commit/be823a27fb04b64a1fa9f6d31fb767960ee6f2db)
@[woosangcho2023](https://github.com/hanghae-99-real-project/back-end/commits?author=woosangcho2023)
woosangcho2023 committed 14 minutes ago

FEAT (조우상) : 마이페이지 수정 기능 추가  @woosangcho2023 woosangcho2023 committed 14 minutes ago

---

(2)services/users.service.js
models/userDaos.js

[fix(조우상): 자잘한 오타 수정](https://github.com/hanghae-99-real-project/back-end/commit/e225700b37ae5f81de28572c6a8f1c1f25dd8fbb)

fix(조우상): 자잘한 오타 수정

---

(2)services/users.service.js
(3)repositories/Users.repository.js
models/userDaos.js

[Revert "fix(조우상): 자잘한 오타 수정"](https://github.com/hanghae-99-real-project/back-end/commit/35a40507ab0166341694bad554a901197b46f988)

Revert "fix(조우상): 자잘한 오타 수정"

---

models/userDaos.js
models/userDaos.js.rej

[FIX(조우상): 서버 구동에 실패해서 이유를 확인하는중](https://github.com/hanghae-99-real-project/back-end/commit/1a9d678d10e5b7f4e3d79b20aef4adcf9685bcdd)

FIX(조우상): 서버 구동에 실패해서 이유를 확인하는중

---

(2)services/users.service.js

[FIX(조우상): userId 값 자동생성 설정이 안되어 있어서 그냥 카카오 id 가져옴](https://github.com/hanghae-99-real-project/back-end/commit/2bd0546e81d1dd1bd48259605a607e79b017ccae)

FIX(조우상): userId 값 자동생성 설정이 안되어 있어서 그냥 카카오 id 가져옴

---

(2)services/users.service.js

[fix(조우상): findone 오류 수정](https://github.com/hanghae-99-real-project/back-end/commit/e6ce5edd92d3cba0cac41aaf5ebbce5e8ec72b35)

fix(조우상): findone 오류 수정

---

(2)services/users.service.js

[fix(조우상): findOne 오류수정](https://github.com/hanghae-99-real-project/back-end/commit/cd098caec694fc4d152d3963f5863c402f9a92b5)

fix(조우상): findOne 오류수정

---

(3)repositories/Users.repository.js

Commits on Jun 8, 2023
[fix(조우상): 소셜로그인 findOne 에러 수정](https://github.com/hanghae-99-real-project/back-end/commit/9f656d8e40b5559c2634d3ad78affdb8b9336365)

Commits on Jun 8, 2023 fix(조우상): 소셜로그인 findOne 에러 수정

---

(3)repositories/Users.repository.js

[fix(조우상): findone 오류수정 최종본(기원)](https://github.com/hanghae-99-real-project/back-end/commit/a1e42e007afe0e86bcb6b3a9af32e576776a742f)

fix(조우상): findone 오류수정 최종본(기원)

---

(3)repositories/Users.repository.js

[fix(조우상): findone 오류수정 찐 최종본(기원)](https://github.com/hanghae-99-real-project/back-end/commit/963482454ac0f403828a9b6395f5d1aa206d2e2b)
@[woosangcho2023](https://github.com/hanghae-99-real-project/back-end/commits?author=woosangcho2023)
woosangcho2023 committed now

fix(조우상): findone 오류수정 찐 최종본(기원)  @woosangcho2023 woosangcho2023 committed now

---

routes/search.routes.js
services/childComment.service.js
services/comment.service.js
services/search.service.js

비밀댓글 비밀대댓글 로직 프론트에서 처리. 백엔드 비밀댓글 비밀대댓글 로직 삭제

FIX: (박준수) 검색, 비밀댓글 비밀대댓글 로직 프론트에서 처리.

---

migrations/20230522082010-create-users.js
models/users.js
repositories/Users.repository.js
services/users.service.js

[fix( 조우상): 유저 대통합](https://github.com/hanghae-99-real-project/back-end/commit/7637192fd90fff2576fb85af336ac0564c64fd73)

fix( 조우상): 유저 대통합

---

services/users.service.js

[fix(조우상): 유저스 대통합](https://github.com/hanghae-99-real-project/back-end/commit/09480bf02bae89420a9e42d5cd2b97778cac399a)

fix(조우상): 유저스 대통합

---

services/users.service.js

console.log("email 타입:", typeof data.kakao_account.email);

console.log("email 타입:", typeof data.kakao_account.email);

---

repositories/Users.repository.js

[fix(조우상): 카카오 대통합](https://github.com/hanghae-99-real-project/back-end/commit/e472fb75f9b15e5b7c39511c445883ba1d7b5da8)

fix(조우상): 카카오 대통합

---

repositories/Users.repository.js
services/users.service.js

[fix(조우상): 유저스 대통합. 카카오로그인 완결](https://github.com/hanghae-99-real-project/back-end/commit/74f4e17ca04dbc20d1729faf1f15b91b476b4eaf)

fix(조우상): 유저스 대통합. 카카오로그인 완결

---

repositories/Users.repository.js
services/users.service.js

[fix(조우상): 소셜로그인 완성 종결. 객체구조분할 끝 엔딩.](https://github.com/hanghae-99-real-project/back-end/commit/f54aff4496179bf7689ae22af75d4e8c42f5cee6)

fix(조우상): 소셜로그인 완성 종결. 객체구조분할 끝 엔딩.

---

migrations/20230522082010-create-users.js
models/users.js
repositories/Users.repository.js

[fix(조우상): 소셜로그인 무한디버깅](https://github.com/hanghae-99-real-project/back-end/commit/30d1f6642b50cb74ba8b3204b7c8993a68790685)

fix(조우상): 소셜로그인 무한디버깅

---

controllers/posts.controller.js
repositories/poo.repository.js
repositories/posts.repository.js
services/poo.service.js
services/posts.service.js

푸박스 위치 등록 시 같은 위치에 있는 푸박스인지 구분, 실종 위치 전체 조회 시 주변 반경 10km 이내의 게시글 제일 상단 조회 후 나머지 랜덤조회

FEAT: (박준수) 푸박스 반경 30미터 이내 등록 불가, 댕파인더 유저의 위치로부터 가까운 순으로 조회

---

controllers/posts.controller.js
modules/user_s3.js
routes/post.routes.js

fix(조우상): 포스트 수정 부분 일부 수정

---

repositories/posts.repository.js
services/posts.service.js

[fix(조우상): 포스트 수정 부분 오류 수정 . 유저 아이디 널값 오류 수정](https://github.com/hanghae-99-real-project/back-end/commit/8eec5d163325bdefaf6862ca04fbb680d7981377)

fix(조우상): 포스트 수정 부분 오류 수정 . 유저 아이디 널값 오류 수정

---

controllers/posts.controller.js
repositories/posts.repository.js

[fix(조우상): 실종신고 날자 추가](https://github.com/hanghae-99-real-project/back-end/commit/fb4b61426ed511bbf47dc74da56c58bae4b7809b)

fix(조우상): 실종신고 날자 추가

---

services/posts.service.js

[fix(조우상): 게시글 수정 권한 오류 수정](https://github.com/hanghae-99-real-project/back-end/commit/5072d5fcad1daed688e6aa4bf7ca5c401da00c87)

fix(조우상): 게시글 수정 권한 오류 수정

---

repositories/Users.repository.js

[fix(조우상): 카카오로그인 디버깅](https://github.com/hanghae-99-real-project/back-end/commit/d71b16639a098f4a92ca40dc4a465649a202da03)

fix(조우상): 카카오로그인 디버깅

---

repositories/Users.repository.js
services/users.service.js

[구현에 집중한 오류 수정](https://github.com/hanghae-99-real-project/back-end/commit/906af93138eefd91330aa8c71ffd5608431feec5)

구현에 집중한 오류 수정

---

controllers/users.controller.js
repositories/Users.repository.js

[fix(조우상): 완전한 성공 확인을 위한 콘솔로그](https://github.com/hanghae-99-real-project/back-end/commit/d9de75c46b0fbd98221401e036d5fdbfbbeb6770)

fix(조우상): 완전한 성공 확인을 위한 콘솔로그

---

repositories/Users.repository.js

[fix(조우상): 소셜로그인 오류 수정 최종](https://github.com/hanghae-99-real-project/back-end/commit/d7c581c33e0aa49488206d217c0c8eb7d0864943)

fix(조우상): 소셜로그인 오류 수정 최종

---

controllers/users.controller.js
services/users.service.js

[fix(조우상) : 소셜로그인 진짜 종결](https://github.com/hanghae-99-real-project/back-end/commit/f8cc010bd0613f6c4d795b457707ea60f1df84a6)

fix(조우상) : 소셜로그인 진짜 종결

---

controllers/posts.controller.js
controllers/users.controller.js
repositories/posts.repository.js
services/users.service.js

[fix(조우상): 초기화](https://github.com/hanghae-99-real-project/back-end/commit/30814c23feddcfbc7640e032fce039fef37e9fdc)

fix(조우상): 초기화

---

controllers/users.controller.js
services/users.service.js

[fix(조우상): 소셜로그인 재수정](https://github.com/hanghae-99-real-project/back-end/commit/d27c48f487c9d5ed1769d6e776f4058c1224ffd3)

fix(조우상): 소셜로그인 재수정

---

modules/s3.js

[fix(조우상): 로스트 포토 사진 수정](https://github.com/hanghae-99-real-project/back-end/commit/14d71cdf9c9f477333219a65cf8489b3f199cef3)

fix(조우상): 로스트 포토 사진 수정

---

modules/s3.js
routes/post.routes.js

[fix(조우상): 경로 수정 마지막.](https://github.com/hanghae-99-real-project/back-end/commit/12f6469785ac9eeb6961c1ea33af763e4ab35cfe)

fix(조우상): 경로 수정 마지막. 

---

services/posts.service.js

fix(조우상): 상태 변환

---

controllers/users.controller.js
repositories/Users.repository.js
routes/post.routes.js
routes/users.routes.js
services/users.service.js

[fix(조우상): api 분할](https://github.com/hanghae-99-real-project/back-end/commit/cfa5ef23609a8b115ed357c25d6c74361a32a0be)

fix(조우상): api 분할

---

controllers/users.controller.js

[fix(조우상): 유저 정보 수정 부분 오타 수정](https://github.com/hanghae-99-real-project/back-end/commit/4cf61ff202c1d85b7304e70c0aa6a2e2366fc3af)

fix(조우상): 유저 정보 수정 부분 오타 수정

---

services/posts.service.js
services/users.service.js

[fix(조우상): end post 설정 오류 수정](https://github.com/hanghae-99-real-project/back-end/commit/d75ec63043b925841eefc778fc8d29fd51bfe680)
[fix(조우상): 콘솔 디버깅 30000트](https://github.com/hanghae-99-real-project/back-end/commit/47e10c4238e60d43617c835da59ff28379b1574b)

fix(조우상): end post 설정 오류 수정

---

controllers/users.controller.js

[fix(조우상): 마이페이지 수정 부분 구조분해 수정](https://github.com/hanghae-99-real-project/back-end/commit/9485d86c4a42ee7d535fbf43d7d111ecc1633d04)

fix(조우상): 마이페이지 수정 부분 구조분해 수정

---

controllers/users.controller.js

Commits on Jun 14, 2023
[fix(조우상): 패스워드 닉네임 받아오는것부터 오류나면 어쩌냐](https://github.com/hanghae-99-real-project/back-end/commit/37a124abbfb49e97deea8d1400fbaf6d9dccdec8)

Commits on Jun 14, 2023 fix(조우상): 패스워드 닉네임 받아오는것부터 오류나면 어쩌냐

---

controllers/users.controller.js

[fix(콘솔로그 디버깅)](https://github.com/hanghae-99-real-project/back-end/commit/6a5ec3a1a868c95e7b41463ace20dc0b5d2a20b7)

fix(콘솔로그 디버깅)

---

routes/users.routes.js

[fix(조우상): 초기화 후 처음부터. 왜 바디에 아무것도 안담기는지 이해가 안되네](https://github.com/hanghae-99-real-project/back-end/commit/c89a686320337449d9d9e71e7069373715e85c3c)

fix(조우상): 초기화 후 처음부터. 왜 바디에 아무것도 안담기는지 이해가 안되네

---

services/posts.service.js

[fix(조우상): getpost에 status 추가](https://github.com/hanghae-99-real-project/back-end/commit/59e5b3d076bfb196220289f1144c050e2b1477a4)

fix(조우상): getpost에 status 추가

---

modules/s3.js

[fix(조우상): 파일 이름 알아보기 콘소로그 디버깅](https://github.com/hanghae-99-real-project/back-end/commit/1530e735ccc9a12366968ae7d300ef3f97d21fe0)

fix(조우상): 파일 이름 알아보기 콘소로그 디버깅

---

modules/s3.js

[fix(조우상): 사진 수정 부분 재수정](https://github.com/hanghae-99-real-project/back-end/commit/7ceb21a145ed12e3022ae92a00225f4805df487a)

fix(조우상): 사진 수정 부분 재수정

---

migrations/20230522081907-create-posts.js
models/posts.js

[fix(조우상): 로스트 푸 시간 설정](https://github.com/hanghae-99-real-project/back-end/commit/d3dc19943282ada9214e7a74cd44a5b9cdc887f0)

fix(조우상): 로스트 푸 시간 설정

---

controllers/users.controller.js

[fix(조우상): 비밀번호 오류 수정](https://github.com/hanghae-99-real-project/back-end/commit/90f24a35062fd95df225be68a538b4b1e0e56dd3)

fix(조우상): 비밀번호 오류 수정

---

controllers/users.controller.js

[fix(조우상): 비밀번호 오류 해결 2ㄴ트](https://github.com/hanghae-99-real-project/back-end/commit/e30cebe76fe133dcdf736d4a35d8463ba09eee9e)

fix(조우상): 비밀번호 오류 해결 2ㄴ트

---

controllers/users.controller.js

[fix(조우상): 비밀번호 수정 3트](https://github.com/hanghae-99-real-project/back-end/commit/1534986c0da2b1c5d7989c9821e43b985aef213a)

fix(조우상): 비밀번호 수정 3트

---

controllers/posts.controller.js
controllers/users.controller.js

[fix(조우상): 댕파인더 시간 추가](https://github.com/hanghae-99-real-project/back-end/commit/2d2a812259ae1dc8d5e630e756a72e98703013ae)

fix(조우상): 비밀번호 수정 4트 fix(조우상): 댕파인더 시간 추가

---

controllers/users.controller.js

[fix(조우상): 비밀번호 수정 7트](https://github.com/hanghae-99-real-project/back-end/commit/339f086524eeb2f99c8c7d90569be126d19406d1)

fix(조우상): 비밀번호 수정 7트

---

controllers/users.controller.js

[fix(조우상): 콘솔로그 하드 디버깅](https://github.com/hanghae-99-real-project/back-end/commit/968aa88f3c302aef5ff3db23802c04733765ed42)

fix(조우상): 콘솔로그 하드 디버깅

---

controllers/users.controller.js

Commits on Jun 15, 2023
[fix(조우상): 유저 비밀번호 수정 8트..](https://github.com/hanghae-99-real-project/back-end/commit/90bd6b99387f0f3b0129af3883fa6c1d9219040c)

Commits on Jun 15, 2023 fix(조우상): 유저 비밀번호 수정 8트..

---

controllers/users.controller.js

[fix(조우상):이름 때문이니? 비밀번호 확인 11트](https://github.com/hanghae-99-real-project/back-end/commit/a8a4bfe4b0098879542c3a7010f99fecb649c213)

fix(조우상):이름 때문이니? 비밀번호 확인 11트

---

controllers/users.controller.js

[fix(조우상): 로그인 수정 12트](https://github.com/hanghae-99-real-project/back-end/commit/291f0cea5b0de0cab5974718270d5e6e1357a5ba)

fix(조우상): 로그인 수정 12트

---

modules/user_s3.js

[fix(조우상): 이거 주석처리 해놓은거 누구야 ;;](https://github.com/hanghae-99-real-project/back-end/commit/d0b8ed5d892d1e18dd59aee0b4c3d59f69b1d939)

fix(조우상): 이거 주석처리 해놓은거 누구야 ;;

---

modules/user_s3.js

[fix(조우상): 디버깅 추가](https://github.com/hanghae-99-real-project/back-end/commit/a395c26acea113ea9b213b5b0ffe323762ae3268)

fix(조우상): 디버깅 추가

---

controllers/users.controller.js
repositories/Users.repository.js
routes/users.routes.js
services/users.service.js

[fix(조우상): 아이디 비밀번호 찾기 기능 추가구현](https://github.com/hanghae-99-real-project/back-end/commit/a885926932f5e4c22f71a2e66b32cb688da024ba)

fix(조우상): 아이디 비밀번호 찾기 기능 추가구현

---

routes/users.routes.js
services/users.service.js

[fix(조우상): 비밀번호 아이디 찾기 로직 수정](https://github.com/hanghae-99-real-project/back-end/commit/24725ebaf8acecba16c34f681d558d0c1e842bcf)

fix(조우상): 비밀번호 아이디 찾기 로직 수정

---

controllers/users.controller.js
repositories/Users.repository.js
services/users.service.js

[fix(조우상): 포지션 추가](https://github.com/hanghae-99-real-project/back-end/commit/f8d3b5262108540a9b1b5cc36c4763b5f646a910)

fix(조우상): 포지션 추가

---

controllers/users.controller.js
repositories/Users.repository.js
services/users.service.js

[fix(조우상): 디버깅 및 수정](https://github.com/hanghae-99-real-project/back-end/commit/1efec7e95594e7e3052b4d8bc04e4ae5fb9b2554)

fix(조우상): 디버깅 및 수정

---

app.js

[fix(조우상): 서버 주소 코스 추가](https://github.com/hanghae-99-real-project/back-end/commit/e228da0dd965473afa1aa3091488c3dfc9fafa28)

fix(조우상): 서버 주소 코스 추가

---

app.js

[fix(조우상): 코스 추가](https://github.com/hanghae-99-real-project/back-end/commit/c878b4eb8b52a84c29fe41aeea8d82e92fdd817f)

fix(조우상): 코스 추가

---

app.js

[fix(조우상): cors 추가](https://github.com/hanghae-99-real-project/back-end/commit/a66b903f6edf856328436c82f153f9d44f48101a)

fix(조우상): cors 추가

---

app.js

[fix(조우상): cors 수정](https://github.com/hanghae-99-real-project/back-end/commit/e195fcdae1dd97ffd5a5d315d3a674461bac1d05)

fix(조우상): cors 수정

---

repositories/Users.repository.js

Commits on Jun 17, 2023
[fix(조우상): 카카오로그인 로직 수정](https://github.com/hanghae-99-real-project/back-end/commit/aa267725d25e6f5f6111b9720a67263a3307194e)

fix(조우상): 카카오로그인 로직 수정

---

repositories/Users.repository.js

[fix(조우상): 카카오로그인 로직 수정](https://github.com/hanghae-99-real-project/back-end/commit/4307de141323ae2448069575f314f0a050db6d7a)
@[woosangcho2023](https://github.com/hanghae-99-real-project/back-end/commits?author=woosangcho2023)
woosangcho2023 committed now

fix(조우상): 카카오로그인 로직 수정  @woosangcho2023 woosangcho2023 committed now

---

repositories/Users.repository.js

[fix(조우상): 소셜 로그인 로직 재수정](https://github.com/hanghae-99-real-project/back-end/commit/66baea159aab2c103da03f4b6c6f9bc64c555878)

fix(조우상): 소셜 로그인 로직 재수정

---

repositories/Users.repository.js

[fix(조우상): 소셜로그인 수정 리트](https://github.com/hanghae-99-real-project/back-end/commit/0bf18c42caefb394104b3d3b247f9a19edb33cbf)

fix(조우상): 소셜로그인 수정 리트

---

controllers/users.controller.js
repositories/Users.repository.js
services/users.service.js

[fix(조우상): 포지션 등록](https://github.com/hanghae-99-real-project/back-end/commit/a3ee8dd76de229fdd257ed73d9dbaafef3aff471)

fix(조우상): 포지션 등록

---

controllers/posts.controller.js

[fix(조우상): 사진 추가 로직](https://github.com/hanghae-99-real-project/back-end/commit/d52ce1315a37a1084943b78afdd0220527b6e312)

fix(조우상): 사진 추가 로직

---

repositories/Users.repository.js

[fix(조우상): 사진이 없을때 사진 추가 로직 추가](https://github.com/hanghae-99-real-project/back-end/commit/ec23c5320466ad76336eef83f65aafdfc310a628)

fix(조우상): 사진이 없을때 사진 추가 로직 추가

---

controllers/posts.controller.js

[fix(조우상): 오류 수정](https://github.com/hanghae-99-real-project/back-end/commit/1be29b1155e88ae10e0f849e2e799dc3344370ec)

fix(조우상): 오류 수정

---

controllers/posts.controller.js
migrations/20230522081907-create-posts.js
models/posts.js

[fix(조우상): findbyid수정](https://github.com/hanghae-99-real-project/back-end/commit/708c43355516253b44d62035c43005d415b2c864)

fix(조우상): findbyid수정

---

repositories/Users.repository.js

[fix(조우상): ㅋㅋㅋ 로직 수정 카카오로그인 성공](https://github.com/hanghae-99-real-project/back-end/commit/0d3cae4ad2da7d53e67fcdb0f21cd092bc14e93f)

fix(조우상): ㅋㅋㅋ 로직 수정 카카오로그인 성공

---

repositories/Users.repository.js
services/users.service.js

[fix(조우상) : 유저포토 수정](https://github.com/hanghae-99-real-project/back-end/commit/bc9df88ef9c3b147054c4977967e17da09503532)

fix(조우상) : 유저포토 수정

---

controllers/posts.controller.js

[fix(조우상): 한개 찾기 수정](https://github.com/hanghae-99-real-project/back-end/commit/00a75c5344be20f3e8fca3662190ac40e6fb66f1)

fix(조우상): 한개 찾기 수정

---

controllers/posts.controller.js

[fix(조우상): 사진좀 같이 넣어주고싶어..](https://github.com/hanghae-99-real-project/back-end/commit/d512ebee0f36ec0aceb5a51a0b2a7bf5eef7c24a)

fix(조우상): 사진좀 같이 넣어주고싶어..

---

controllers/posts.controller.js

[fix(조우상): 디버깅 코드 추가](https://github.com/hanghae-99-real-project/back-end/commit/bf374e0c7b7fe2812993e6288a70e8661a956d69)

fix(조우상): 디버깅 코드 추가

---

controllers/posts.controller.js

[fix(조우상): 이정도로 만족하자](https://github.com/hanghae-99-real-project/back-end/commit/092445a40b962bdd60f4ad47f77c0ab1ce21ac86)

fix(조우상): 이정도로 만족하자

---

controllers/posts.controller.js

[fix(조우상): 사진 보내기 수정](https://github.com/hanghae-99-real-project/back-end/commit/3ad9b89ea9ce65232b49bf9a08382882ed4223cc)

fix(조우상): 사진 보내기 수정

---

controllers/posts.controller.js

[fix(조우상): 이렇게 해보면? rty](https://github.com/hanghae-99-real-project/back-end/commit/d56a7b432803261a376a59059b81f6ae3e45ffa0)

fix(조우상): 이렇게 해보면? rty

---

routes/index.js
scripts/deploy.sh
scripts/karyl.sh

[fix(조우상): 주석처리 밑 쉘스크립트 일부 재수정 리펙토링](https://github.com/hanghae-99-real-project/back-end/commit/a6bee2797b03602992b6d4d1c7b748b956e82403)

fix(조우상): 주석처리 밑 쉘스크립트 일부 재수정 리펙토링

---

controllers/users.controller.js
repositories/Users.repository.js
services/users.service.js

[fix(조우상): 리팩토링 1트](https://github.com/hanghae-99-real-project/back-end/commit/209562fc91f69b2304f483619173b73fac0338a6)

fix(조우상): 리팩토링 1트

---

controllers/users.controller.js
repositories/Users.repository.js

[fix(조우상): 오류수정 2](https://github.com/hanghae-99-real-project/back-end/commit/e84dae65ecbbcef6e8021a193b8ddac40ca2a94f)

fix(조우상): 오류수정 2

---

controllers/users.controller.js
repositories/Users.repository.js
services/users.service.js

[fix(조우상): 회원가입 부분 오류 수정](https://github.com/hanghae-99-real-project/back-end/commit/dd5636e66f624be19e774ee0491f0f9a04b4797b)

fix(조우상): 회원가입 부분 오류 수정

---

services/users.service.js

[fix(조우상): 병합 해결](https://github.com/hanghae-99-real-project/back-end/commit/13b0bb8f079011daae9b232b5a6fa4e98c4c0ff6)

fix(조우상): 병합 해결

---

repositories/Users.repository.js
services/users.service.js

[fix(조우상): 회원가입 오류수정 재시도](https://github.com/hanghae-99-real-project/back-end/commit/3ab4ba527d1b0be4ada5e567c03fe523fadde9e7)

fix(조우상): 회원가입 오류수정 재시도

---

services/users.service.js

fix(조우상): 리펙토링 로그인 부분 오류수정

---

services/users.service.js

fix(조우상): 리펙토링 및 회원가입 오류 수정

---

controllers/users.controller.js
repositories/Users.repository.js
services/posts.service.js
services/users.service.js

[fix(조우상): 상세 포스트 조회 부분 오류 수정](https://github.com/hanghae-99-real-project/back-end/commit/cbac59379077be65d81466f4f2aeb6b858950a35)

fix(조우상): 카카오로그인 토큰 저장 로직 추가fix(조우상): 상세 포스트 조회 부분 오류 수정

---

services/posts.service.js

[fix(조우상): 철자오류 수정](https://github.com/hanghae-99-real-project/back-end/commit/c45d296e21f83562e2649581076563cbcd0b2777)

fix(조우상): 철자오류 수정

---

test/unit/testcontrollers/users.controller.unit.spec.js

feat(조우상): 작성한 테스트코드 (주석처리)
